MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
PROGRAMMABLE_BUTTON_ENABLE = yes
SWAP_HANDS_ENABLE = yes
KEY_LOCK_ENABLE = yes
COMBOS_ENABLE = yes

# saving space
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
UNICODE_ENABLE = no
TAP_DANCE_ENABLE = no
ENCODER_ENABLE = no
